### ISSUE TITLE
Just wanna know if you use any image tool like carbon?

### ISSUE THREAD

**Issue by zhang6464** [GoogleChromeLabs/size-plugin#11]
https://camo.githubusercontent.com/806eb206a76f2453f3160eb2e56f1d4a2aaa589f/68747470733a2f2f692e696d6775722e636f6d2f33625742724a6d2e706e67
I mean this image,  how do you generate it? just screen cut?
I really like the style，if there's a generate tool, very appreciated for supplying the name, thanks!

**Comment by developit** [comment]
It's a screenshot of the vscode built-in terminal, which I then edited using [Figma](https://figma.com).
