### ISSUE TITLE
Emits all dependencies files if output path is set to project root

### ISSUE THREAD

**Issue by samundrak** [GoogleChromeLabs/size-plugin#14]
In webpack v4 it will create dist folder if not defined, but if we explicitly set the output path to the root of the project then this plugin will console log all the dependencies and its diff.
Problem is seen on glob it fetches all files and even there will be an error of like can't read on the directory.

![image](https://user-images.githubusercontent.com/3079452/44722043-89c18e00-aaeb-11e8-83ff-74ee8beeac8c.png)

**Comment by developit** [comment]
Ack! That's a tough one - in order to list removed output files (things that were in the previous build but are now deleted) we need to crawl the old directory structure.

I wonder - if the plugin ignored `node_modules`, `src` and `test(s)`, would that work for your case?

**Comment by samundrak** [comment]
AH Yes, we can ignore `node_modules`, `src` explicitly, but it might confuse many users who had set the output to `root`. but very fewer people will do that in my opinion.
