### ISSUE TITLE
TypeScript types

### ISSUE THREAD

**Issue by nickytonline** [GoogleChromeLabs/size-plugin#20]
First off, thanks for the plugin. 👍

I'm going to be creating the TypeScript types for this package as it's used in the Refined GitHub extension, https://github.com/sindresorhus/refined-github/pull/1987#discussion_r279021201, where I recently helped convert the project to TypeScript.

My question is, would you be willing to host the types in this repository if I put up a PR or am I better off sending a PR to the DefinitelyTyped project?

**Comment by developit** [comment]
@nickytonline yup, happy to host types here.

**Comment by developit** [comment]
Fixed in [3.0.0](https://github.com/GoogleChromeLabs/size-plugin/releases/tag/3.0.0).
