### ISSUE TITLE
Add option to show real build size not gzipped

### ISSUE THREAD

**Issue by jimblue** [GoogleChromeLabs/size-plugin#23]
Hi,

When comparing real assets size to the output of your plugin I see a huge difference.

I guess it's because size-plugin show gzipped sizes...
This can be confusing or non relevant depending of the use case and it could be nice to add a column to the output. (to display both compressed and real assets size)

Or maybe just an option to choose what too show?!

Tks !!

**Comment by developit** [comment]
If we do this, I'd like to show uncompressed / gzip / brotli, and have a configuration option that allows specifying which to calculate + show.

**Comment by kuldeepkeshwar** [comment]
How about something like
```
new SizePlugin({
 compression:['gzip','brotli'] // default is uncompressed
})
```
which outputs
```
                           file ⏤  brotli  gzip   uncompressed 
 bda2fc19cbf02a35c1b5.worker.js ⏤  20kB    25kB    80 kB
          editor.chunk.*****.js ⏤  18kB    22kB    65.8 kB

```
We also need to think about delta

**Comment by jimblue** [comment]
:100: for adding delta

**Comment by timbomckay** [comment]
Is this plugin still maintained? Is there an alternative?

**Comment by developit** [comment]
Anyone can submit a pull request to add functionality, no need to wait for me!
