### ISSUE TITLE
ETA on new version

### ISSUE THREAD

**Issue by tanem** [GoogleChromeLabs/size-plugin#26]
Hey there,

I see #21 was merged a while ago :tada: Is there an ETA for when a new npm version will be published?

Cheers.

**Comment by kuldeepkeshwar** [comment]
@tanem Published 🚀 in `2.0.0`

For integration with [size-plugin-bot](https://github.com/kuldeepkeshwar/size-plugin-bot), check [here](https://github.com/kuldeepkeshwar/size-plugin-bot#usage)

**Comment by tanem** [comment]
Thanks @kuldeepkeshwar!
