### ISSUE TITLE
Webpack 3 compatibility?

### ISSUE THREAD

**Issue by elektronik2k5** [GoogleChromeLabs/size-plugin#3]
Awesome project! It is one of those many DX features, which CRA gets right - only generalized for everyone's benefit. Thank you! :)
Is there a chance to make the plugin compatible with `webpack@3`? Many projects are still using it (including CRA) and can benefit greatly from your plugin.

**Comment by developit** [comment]
Definitely. Just need to tweak the tappable calls.

**Comment by developit** [comment]
Fixed!
