### ISSUE TITLE
Not saving to file for webpack 3

### ISSUE THREAD

**Issue by t47io** [GoogleChromeLabs/size-plugin#32]
Using webpack `3.12.0`. Even with `{ writeFile: true }` in options, no json file is written to disk. I tracked down the problem is here:
https://github.com/GoogleChromeLabs/size-plugin/blob/master/src/index.mjs#L158

For webpack 3, `compiler.options.mode` is `undefined`, which leads to no-op when `writeToDisk`: https://github.com/GoogleChromeLabs/size-plugin/blob/master/src/index.mjs#L118-L131

**Comment by t47io** [comment]
It seems there is no `mode` info at all for webpack 3 `options`, so one way to fix is to add optional `mode` override in `SizePlugin(options)`. Ideas? @developit

**Comment by developit** [comment]
Fixed in [3.0.0](https://github.com/GoogleChromeLabs/size-plugin/releases/tag/3.0.0).
