### ISSUE TITLE
Bottom

### ISSUE THREAD

**Issue by Mobilpadde** [GoogleChromeLabs/size-plugin#4]
Would it be possible to show in the bottom of everything? I have to scroll up to see the result :-1: 

Other than that, great plugin! :+1:

**Comment by developit** [comment]
Good idea! I have to look into the timing there. I actually think it might be partially based on where in your plugins list it gets placed! Haha.

**Comment by DorianGrey** [comment]
Suppose it would be better to use the `done` hook instead of `afterEmit`. Several plugins for formatting build stats output are using `done`, thus all of them would print their output _after_ the one from this plugin.

**Comment by developit** [comment]
@DorianGrey Hmm - does that hook pass the `compilation` instance like `afterEmit` does? If so it'd be a trivial change.

**Comment by DorianGrey** [comment]
No, but it provides the `stats` object - see docs: https://webpack.js.org/api/compiler-hooks/#done
The `compilation` instance is still available on that object, but it also provides simpler ways to access the asset stats information.
Something like:
```
stats.toJson({}, true).assets
```
I'm currently using this hook in [a more complex display plugin](https://github.com/DorianGrey/react-ts-playground/blob/master/config/webpack/plugins/BuildStatsFormatterPlugin.js), and it works fine.

**Comment by agorilla** [comment]
Any update on this? 

Would be a very useful feature to place the stat output at the end.
I'm using Webpack 4 and regardless where I place the plugin inside the plugins array it gets printed out right at the top.

**Comment by developit** [comment]
Fixed in [3.0.0](https://github.com/GoogleChromeLabs/size-plugin/releases/tag/3.0.0).
