### ISSUE TITLE
Store the output

### ISSUE THREAD

**Issue by mick-feller** [GoogleChromeLabs/size-plugin#6]
More of a feature request, anyway i can extract it and store the sizing over multiple builds? So i can historically track down major jumps?

Let it write to a json or something that i can then graph out in jenkins or in local for analysis?

**Comment by developit** [comment]
I love this idea. I'm thinking the plugin could create a dotfile containing the stats, which would include historical file sizes.

**Comment by mick-feller** [comment]
Yeah whichever file it might be, anything can be imported for that matter. I'll see if i have some time to do a PR this week.

**Comment by mick-feller** [comment]
I just send you the PR let me know what you think. It's a first pass i can always make adjustments

**Comment by developit** [comment]
@mick-feller sorry for falling so behind on this! I'll get to reviewing your PR ASAP.

**Comment by developit** [comment]
Added in #21
